version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: ["entrypoint.sh"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # This assumes your Django code is in a folder named 'app'
    environment:
      - DJANGO_SETTINGS_MODULE=cicd_project.settings  # Replace 'your_project' with your actual Django project name
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pipline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
